import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import MessageBar from "./MessageBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Truck Accessory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div>
          <div>
            <MessageBar />
          </div>
          <div className="sticky top-0">
            <NavBar />
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
